### ISSUE TITLE
`This bot can't join more servers` error when trying to add to my server

### ISSUE THREAD

**Issue by gildotdev** [matthewzring/CyberScores#2] opened 2024-12-17 15:23 UTC
![Screenshot 2024-12-17 at 10 21 00 AM](https://github.com/user-attachments/assets/a94ea50b-6ef9-4f6f-86b6-bc511a110481)

```
This bot can't join more servers as it has not been verified or is requesting gateway intents it has not been verified for. Ask the bot's developer about https://dis.gd/bot-verification so you can add it to your server!
```

**Comment by matthewzring** [comment] 2024-12-17 22:39
Duplicate of #1

**Closed as not planned by matthewzring** 2024-12-17 22:39 UTC
